# Generated by Django 2.0.6 on 2018-06-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockapp', '0002_auto_20180621_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocktable',
            name='isPrivate',
            field=models.IntegerField(default=0),
        ),
    ]
